### ISSUE TITLE
241015

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#1]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [x] 코테 스터디 2문제
- [x] 큰돌 1주차 3문제
- [x] 우테코 미션 확인
- [x] 토비의 스프링 테스트 강의
- [x] 필라테스
- [x] SSAFY 강의 복습

## 📅 이번 주 해야 할 일
- [ ] 우테코 1주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [ ] null
- [ ] null

## ✏️ 메모
- 사용자의 입력에 대해 고민해보기
    - 사용자는 우리의 예상을 항상 뛰어넘는다.
- Git, GitHub, IDE 등 실제 개발을 위한 환경에 익숙해진다.
- 교육 분야에 맞는 프로그래밍 언어를 사용하여 간단한 문제를 해결한다.

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 오늘 하루 원하는 목표를 다 이룸
- 기록하는 것을 시작함

## 😓 Learned (배운 점)
- 기능명세서란 무엇인가
- 커밋 컨벤션을 어떻게 작성하는 것인가

## 😕 Lacked (아쉬운 점)
- 포모도로 기법을 아직 사용하지 못 함
- 토비의 스프링을 원하는 만큼 강의를 듣지 못한 것

## 🔧 Longed for (개선할 점)
- 집중과 휴식의 균형이 필요함
