### ISSUE TITLE
241030

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#11]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [x] 이팩티브 자바 - 아이템 34
- [x] 코테 스터디 1문제
- [x] SSAFY 강의 복습
- [x] 우테코 3주차 미션 요구사항 정리 및 코드 작성
- [ ] 우테코 2주차 코드리뷰
- [x] 최종 프로젝트 아이디어 회의

## 📅 이번 주 해야 할 일
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편
- [ ] 밀린 SSAFY 강의 완료

## 🏆 완료한 일
- [ ] null
- [ ] null

## ✏️ 메모
- `ENUM`에 대해 배워보자

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 기능 목록 작성에 익숙해짐.
- 다른 날보다 시간을 효율적으로 사용함.

## 😓 Learned (배운 점)
- JUint5의 어노테이션에 대해 배움.
- enum에 사용 이유에 대해 공부함.

## 😕 Lacked (아쉬운 점)
- 어제는 다 하지 못했으니, 할 일을 최대한 해보자.
- 하노이의 탑 원리는 이해했는데... 코드 구현을 못 함.

## 🔧 Longed for (개선할 점)
- 시간을 효율적으로!
