### ISSUE TITLE
241031

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#12]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [ ] 코테 스터디
- [x] SSAFY 강의 복습
- [x] 우테코 3주차 미션 코드 작성
- [ ] 우테코 2주차 코드리뷰
- [x] 최종 프로젝트 아이디어 회의

## 📅 이번 주 해야 할 일
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편
- [ ] 밀린 SSAFY 강의 완료

## 🏆 완료한 일
- [ ] null
- [ ] null

## ✏️ 메모
- 쓰레기 코드라도 구현에 집중하자.

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 
- 

## 😓 Learned (배운 점)
- 
- 

## 😕 Lacked (아쉬운 점)
- 
- 

## 🔧 Longed for (개선할 점)
-
