### ISSUE TITLE
241016

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#3]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [x] 코테 스터디 2문제
- [x] 큰돌 2주차 3문제
- [x] 우테코 미션 구현_01
- [ ] 토비의 스프링 테스트 강의
- [x] SSAFY 강의 복습

## 📅 이번 주 해야 할 일
- [ ] 우테코 1주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [ ] 작업 1
- [ ] 작업 2

## ✏️ 메모
- 중요 사항 1
- 중요 사항 2

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 저녁 먹고 혈당스파이크를 맞는 와중에도 산책으로 잠을 이겨냄
- `MVC 패턴`을 이용해서 미션을 수행하려고 노력하고, 고민거리를 잘 메모해두었음.

## 😓 Learned (배운 점)
- 미션을 진행하면서 기능 목록을 다시 작성하였는데, 첫 시작이 매우 힘들었음. 
- `Interceptor`에 대해 배움(`로그인`과 같은 기능에 사용).

## 😕 Lacked (아쉬운 점)
- `포모도로 기법`을 아직 사용하지 못 함
- 오늘의 할일을 1가지 남겨둠

## 🔧 Longed for (개선할 점)
- 점심 이후의 시간에 너무 나른함을 많이 느낌...
