### ISSUE TITLE
241017

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#4]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [x] 코테 스터디 3문제
- [x] 우테코 미션 구현_02
- [x] SSAFY 강의 복습

## 📅 이번 주 해야 할 일
- [x] 우테코 1주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [ ] 작업 1
- [ ] 작업 2

## ✏️ 메모
- 중요 사항 1
- 중요 사항 2

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 
- 

## 😓 Learned (배운 점)
- 
- 

## 😕 Lacked (아쉬운 점)
- 
- 

## 🔧 Longed for (개선할 점)
-
