### ISSUE TITLE
241021

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#5]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [ ] 코테 스터디 2문제
- [x] 우테코 미션 완료
- [ ] SSAFY 강의 복습

## 📅 이번 주 해야 할 일
- [ ] 우테코 2주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [ ] null
- [ ] null

## ✏️ 메모
- 회고하기

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 내가 만들어놓은 테스트케이스를 모두 통과함.
- 코드는 미숙해도 미션을 완료함.

## 😓 Learned (배운 점)
- 결합도에 대해 고민하며, 메소드를 하나의 책임을 가지도록 최대한 노력함.
- 사용자의 입력에 대해 고민하는 과정을 가짐(test).

## 😕 Lacked (아쉬운 점)
- 저번 주 해야할 일을 다 하지 못 함.
- todolist를 주말에 쉬었던 점.

## 🔧 Longed for (개선할 점)
- 주말이라는 귀중한 시간을 어떻게 보낼 것인지 다시 생각하자.
