### ISSUE TITLE
241022

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#6]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [x] 코테 스터디 4문제
- [x] 우테코 2주차 미션 요구사항 분석
- [x] SSAFY 강의 복습
- [x] 필라테스

## 📅 이번 주 해야 할 일
- [ ] 우테코 2주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [ ] null
- [ ] null

## ✏️ 메모
- 회고하기

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 디스코드를 통해 코드 리뷰를 받고, 리뷰를 하며 새로운 점을 배움.
- 졸리는 시간을 산책을 통해 이겨냄.

## 😓 Learned (배운 점)
- 메소드가 SRP를 지키게 코드를 작성해야 유지보수, 확장성이 생긴다는 사실.
- 코드 리뷰를 하며, 다른 사람들의 논리의 흐름을 읽는 방법을 조금 익힘.

## 😕 Lacked (아쉬운 점)
- 프로젝트 아이디어가 잘 나오지 않음.
- 개인 공부가 진행되지 못한 점.

## 🔧 Longed for (개선할 점)
- 시간을 더욱 쪼개서 써보기.
