### ISSUE TITLE
241023

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#7]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [ ] 코테 스터디 2문제
- [x] 우테코 2주차 미션 기능목록 작성 및 코드 작성
- [ ] SSAFY 강의 복습

## 📅 이번 주 해야 할 일
- [ ] 우테코 2주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [x] 피드백 주고 받기
- [ ] null

## ✏️ 메모
- 피드백에 대해 고민하고 공부하기

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 요구사항 분석에 시간을 많이 들여서 고민한 점.
- 최종 프로젝트 아이디어 다양하게 제시하기.

## 😓 Learned (배운 점)
- 다른 사람 코드를 읽어보며 검증에 대한 부분을 따로 빼내어 관리한다면 유지보수 및 확장성을 위한 코드가 될 수 있음.
- MVC 패턴에서 각각의 역할에 대해 더 알아보는 시간을 가짐.

## 😕 Lacked (아쉬운 점)
- 코테 문제를 풀고 싶었지만, 풀이방법이 생각나지 않아 풀지 못 함.
- 미션 요구사항을 잘 분석했다고 생가했지만, `아무것도 입력하지 않았을 때`를 놓침.

## 🔧 Longed for (개선할 점)
- 사용자의 입력에 아무것도 들어오지 않을 수 있다는 생각하기.
