### ISSUE TITLE
241024

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#8]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [ ] 코테 스터디 2문제
- [ ] 우테코 2주차 미션 코드 작성 01
- [ ] SSAFY 강의 복습

## 📅 이번 주 해야 할 일
- [ ] 우테코 2주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [x] 피드백 주고 받기
- [ ] null

## ✏️ 메모
- 요구사항에 대한 테스트 케이스에 대해 생각해보기

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 
- 

## 😓 Learned (배운 점)
- 
- 

## 😕 Lacked (아쉬운 점)
- 
- 

## 🔧 Longed for (개선할 점)
- 이거 작성 잘하기....
