### ISSUE TITLE
241029

### ISSUE THREAD

**Issue by SON1205** [SON1205/TIL#9]
# 📝 To-Do List

## 📅 오늘 해야 할 일
- [x] 코테 스터디 3문제
- [ ] 우테코 3주차 요구사항 정리
- [x] SSAFY 강의 복습
- [x] 최종프로젝트 아이디어 회의
- [ ] 우테코 코드 리뷰

## 📅 이번 주 해야 할 일
- [ ] 우테코 3주차 미션
- [ ] 토비의 스프링
- [ ] 자바의 정석 1편

## 🏆 완료한 일
- [ ] null
- [ ] null

## ✏️ 메모
- 테스트를 잘하는 법 고민해보자

# 📆 4L 회고

## 😄 Liked (잘한 점)
- 아이디어 회의를 무사히 마침.
- SSAFY 공부를 놓치 않음.

## 😓 Learned (배운 점)
- MVC 패턴을 왜 사용하는지에 대해 계속 고민해 보며, 컨트롤러의 역할을 공부함.
- 아이디어 회의를 원활하게 이어가는 것에 대해 고민해 봄.

## 😕 Lacked (아쉬운 점)
- 기록이 24일 이후 뚝 끊김.
- 매주 해야할 일에서 한 가지만 열심히 하고, 나머지는 열심히 하지 않음.

## 🔧 Longed for (개선할 점)
- 꾸준한 기록을 남기자.
